import type { Metadata } from "next";
import "../globals.css";
import { Container } from "@/src/components/Container";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Container className="min-h-screen  pt-24 pb-12 ">
  
      {children}
    </Container>
  );
}
